# Generated by Django 2.0.13 on 2019-07-10 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=120)),
                ('contactName', models.CharField(max_length=120)),
                ('contactTitle', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('region', models.CharField(max_length=32)),
                ('postalCode', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('fax', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=120)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
